name: Build & Release

on:
  push:
    tags:
      - 'v*'  # dispara ao criar tag v1.0.0, v1.0.1, etc.
  workflow_dispatch:  # permite rodar manualmente

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install
          npm install --save-dev electron electron-builder

      - name: Build Electron app
        run: npm run dist
        env:
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          PGDATABASE: postgres
          PGPORT: 5432

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: alianca-software-windows
          path: |
            dist/*.exe
            dist/*.exe.blockmap

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.exe
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}